# Generated by Django 4.2.1 on 2023-07-06 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='created_at',
            new_name='stocked_at',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='created_by',
            new_name='stocked_by',
        ),
    ]
